config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'

  namespace :admin do
    resources :users
  end

  resources :tasks do
    collection do
      post :confirm
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :labels, only: [:new, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskTraining</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Allerta+Stencil&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- sessionログインで、メールアドレスが存在しなかったらフラッシュメッセージ -->
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <!-- sessionログイン前とログイン後の出し分け -->
    <% if logged_in? %>
      <header class="navbar navbar-header clearfix row">
        <h1 class="logo"><%= link_to 'Task Training', tasks_path %><span>-&nbsp;はじめよう、タスク管理&nbsp;-</span></h1>
        <div class="new_btn">
          <p><%= link_to new_task_path do %>
                <i class="fas fa-plus-circle"></i>
          <% end %></p>
        </div>
        <ul>
          <li><%= link_to 'プロフィール', user_path(current_user.id) %></li>
          <li><%= link_to 'ログアウト', session_path(current_user.id), method: :delete %></li>
        <% if @current_user.admin.present? %>
          <!-- adminの場合 -->
          <li><%= link_to '管理者メニュー', admin_users_path %></li>
          <li><%= link_to 'ラベル作成', new_label_path %></li>
        <% end %>
        </ul>
      </header>
    <% else %>
      <header class="login-page">
        <h1 class="logo">Task Training</h1>
        <p>-&nbsp;はじめよう、タスク管理&nbsp;-</p>
        <!--<ul>
          <li><%= link_to 'サインアップ', new_user_path %></li>
          <li><%= link_to 'ログイン', new_session_path %></li>
        </ul>-->
      </header>
    <% end %>

    <div class="wrapper container">
      <div class="row">
      <%= yield %>
      </div>
    </div>

    <%# <footer>
      <p>Task Training</p>
    </footer>  %>
  
  </body>
</html>